server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }


    location /france {
        alias /usr/share/nginx/html/travels/france/france.html;
    }
    location /france/toulouse {
        alias /usr/share/nginx/html/travels/france/toulouse.html;
    }
    location /france/paris {
        alias /usr/share/nginx/html/travels/france/paris.html;
    }
    location /france/collioure {
        alias /usr/share/nginx/html/travels/france/collioure.html;
    }
    location /france/leucate {
        alias /usr/share/nginx/html/travels/france/leucate.html;
    }
    location /france/lyon {
        alias /usr/share/nginx/html/travels/france/lyon.html;
    }
    location /france/niort {
        alias /usr/share/nginx/html/travels/france/niort.html;
    }
    location /france/pyrenees {
        alias /usr/share/nginx/html/travels/france/pyrenees.html;
    }
    location /france/re {
        alias /usr/share/nginx/html/travels/france/re.html;
    }

    
    location /korea {
        alias /usr/share/nginx/html/travels/korea/korea.html;
    }
    location /korea/busan {
        alias /usr/share/nginx/html/travels/korea/busan.html;
    }
    location /korea/daegu {
        alias /usr/share/nginx/html/travels/korea/daegu.html;
    }
    location /korea/daejeon {
        alias /usr/share/nginx/html/travels/korea/daejeon.html;
    }
    location /korea/gwangju {
        alias /usr/share/nginx/html/travels/korea/gwangju.html;
    }
    location /korea/jeju {
        alias /usr/share/nginx/html/travels/korea/jeju.html;
    }
    location /korea/jochiwon {
        alias /usr/share/nginx/html/travels/korea/jochiwon.html;
    }
    location /korea/sejong {
        alias /usr/share/nginx/html/travels/korea/sejong.html;
    }
    location /korea/seoul {
        alias /usr/share/nginx/html/travels/korea/seoul.html;
    }
    location /korea/suwon {
        alias /usr/share/nginx/html/travels/korea/suwon.html;
    }
    

    location /china {
        alias /usr/share/nginx/html/travels/china/china.html;
    }
    location /china/beijing {
        alias /usr/share/nginx/html/travels/china/beijing.html;
    }
    location /china/shanghai {
        alias /usr/share/nginx/html/travels/china/shanghai.html;
    }
}
