name: CI-CD Workflow

on:
  push:
    branches: [ "dev" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: autoneeip/adrien_website:dev-latest

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: |
        docker build . -t $DOCKER_REGISTRY
      
    - name: Docker Push
      run: docker push $DOCKER_REGISTRY
